# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ace8a1f9e961b916e24dde5a9113b31e1d280d19ebe4a6f9c241ea4fb3dbdab32a6d92d650ac7fab0126d82b92bf85502140f0648027e02dc66e010029ef25a

test:
  secret_key_base: 2e253125ffc16ca9bd686e81dde549a1562870033429630e86793c75f7d7e47b38371e65654dd621f9f6a40d46454901c41ebe38c1e4aa47879e5e15cfb9d841

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
